name: Manual Sync with Subdirectories

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean target directories
        run: |
          rm -rf WatchTool
          rm -rf update/WatchTool_Wear
          mkdir -p WatchTool
          mkdir -p update/WatchTool_Wear

      - name: Sync WatchTool with subdirs
        env:
          BASE_URL: "https://mcbug087.eu.org/WatchTool"
        run: |
          echo "步骤1: 下载文件列表"
          wget -q $BASE_URL/filelist.txt -O WatchTool/filelist.txt
          
          echo "步骤2: 处理文件和子目录"
          cd WatchTool
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              # 创建必要的子目录
              dir_path=$(dirname "$file")
              if [ ! -d "$dir_path" ]; then
                mkdir -p "$dir_path"
                echo "创建目录: $dir_path"
              fi
              
              # 下载文件
              echo "下载文件: $file"
              wget -q --show-progress "$BASE_URL/$file" -O "$file"
            fi
          done < filelist.txt
          cd ..

      - name: Sync WatchTool_Wear
        env:
          BASE_URL: "https://mcbug087.eu.org/update/WatchTool_Wear"
        run: |
          wget -q $BASE_URL/filelist.txt -O update/WatchTool_Wear/filelist.txt
          cd update/WatchTool_Wear
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              mkdir -p "$(dirname "$file")"
              wget -q --show-progress "$BASE_URL/$file" -O "$file"
            fi
          done < filelist.txt
          cd ../..

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git status
          git commit -m "同步更新: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main